### ISSUE TITLE
Ошибка при запуске на Linux

### ISSUE THREAD

**Issue by ivanthecrazy** [TinkoffCreditSystems/invest-openapi-js-sdk#8]
На Windows все работает отлично, переношу на сервер и получаю:

```
Error: Cannot find module './build/OpenAPI'    at Function.Module._resolveFilename 
(internal/modules/cjs/loader.js:636:15)    at Function.Module._load 
(internal/modules/cjs/loader.js:562:25)    at Module.require (internal/modules/cjs/loader.js:692:17)    at 
require (internal/modules/cjs/helpers.js:25:18)    at Object.<anonymous> 
(/home/app/giraff_trade/node_modules/@tinkoff/invest-openapi-js-sdk/index.js:2:18)    at Module._compile (internal/modules/cjs/loader.js:778:30)    at Module._compile 
(/home/app/giraff_trade/node_modules/pirates/lib/index.js:99:24)    at Module._extensions..js 
(internal/modules/cjs/loader.js:789:10)    at Object.newLoader [as .js] 
(/home/app/giraff_trade/node_modules/pirates/lib/index.js:104:7)    at Module.load 
(internal/modules/cjs/loader.js:653:32)
```

проблема в регистре - есть файл `build/openApi.js`, но не `build/OpenAPI.js`. А линукс (и вроде как мак тоже) - чувствительны к регистру. При переименовывании файла все ок

**Comment by ZigGreen** [comment]
Да, поправил багу. 
в версии 1.1.1
