### ISSUE TITLE
Ошибка при вызове функции отмены, возвращаемойм api.candle()

### ISSUE THREAD

**Issue by lotar659** [TinkoffCreditSystems/invest-openapi-js-sdk#88]
Код
` const unsub = api.candle({figi}, (x) => {
           console.log(x)
        });
        unsub();`

Ошибка 
`(node:63946) UnhandledPromiseRejectionWarning: TypeError: this.off is not a function
    at /Users/zazumedia/Documents/trading-bot/node_modules/@tinkoff/invest-openapi-js-sdk/build/OpenAPI.cjs.js:168:18
    at /Users/zazumedia/Documents/trading-bot/index.js:54:13
    at Generator.next (<anonymous>)
    at fulfilled (/Users/zazumedia/Documents/trading-bot/index.js:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
`

**Comment by lotar659** [comment]
Решилось обновлением node
