### ISSUE TITLE
Помогите? что это за ошибка?

### ISSUE THREAD

**Issue by co-o-ox** [TinkoffCreditSystems/invest-openapi-js-sdk#94]
Выдает вот такую ошибку:
FetchError: request to https://api-invest.tinkoff.ru/openapi/market/search/by-ticker?ticker=RIG failed, reason: read ETIMEDOUT
    at ClientRequest.<anonymous> (/Users/maksimsavcenko/Desktop/untitled5/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

**Comment by ZigGreen** [comment]
Проблема еще актуальна?

**Comment by co-o-ox** [comment]
> Проблема еще актуальна?

Эта проблема уже нет/
Но есть другая




FetchError: invalid json response body at https://api-invest.tinkoff.ru/openapi/orders reason: Unexpected end of JSON input
    at /Users/maksimsavcenko/Desktop/untitled5/node_modules/node-fetch/lib/body.js:48:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at OpenAPI.makeRequest (/Users/maksimsavcenko/Desktop/untitled5/node_modules/@tinkoff/invest-openapi-js-sdk/build/OpenAPI.cjs.js:249:19) {
  type: 'invalid-json'
}


Эта ошибка появляется вообще непонятна почему

**Comment by co-o-ox** [comment]
Решается только перезагрузкой компьютера

**Comment by co-o-ox** [comment]
Эта ошибка начала появляться, когда я запустил такую же программу на ИИС. 
те иногда запускаю вторую консоль вылетает такая ошибка в обоих, иногда работают нормально

**Comment by co-o-ox** [comment]
Прописал аккаунт получаю теперь вот такую ошибку

FetchError: invalid json response body at https://api-invest.tinkoff.ru/openapi/orders?brokerAccountId=2037672579 reason: Unexpected end of JSON input
    at /Users/maksimsavcenko/Desktop/untitled5/node_modules/node-fetch/lib/body.js:48:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at OpenAPI.makeRequest (/Users/maksimsavcenko/Desktop/untitled5/node_modules/@tinkoff/invest-openapi-js-sdk/build/OpenAPI.cjs.js:249:19) {
  type: 'invalid-json'
}

Она начала появляться после открытия ИИС

**Comment by co-o-ox** [comment]
Эта ошибка появляется когда я запускаю вторую консоль для счета на ИИС, в обоих консолях выпадает такая ошибка. ПОдскажите как этого избежать?
Это может быть связано с ограничением количества запросов?

**Comment by penoplaster83** [comment]
Меня эта ошибка мучает при одной рабочей консоли. 
Появляется при ряде разных запросов:
Отмена ордера, Новый ордера, Запрос списка ордеров (самое частое. При ~ 95% попыток ошибка)

**Comment by ZigGreen** [comment]
duplicates: #96
